---
title: Using simulation to optimize the sampling design of fisheries-independent trawl surveys
author: "Paul M. Regular, Fran Mowbray, et al.?"
date: "Fisheries and Oceans Canada, Northwest Atlantic Fisheries Center, 80 East White Hills, St. John's, Newfoundland and Labrador, A1C 5X1, Canada"
output: 
  bookdown::word_document2:
    reference_docx: template.docx
bibliography: references.bib
csl: ices-journal-of-marine-science.csl
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Abstract

A central question to fish stock assessments is: how many samples are needed to adequately represent the population being monitored? For assessments based on trawl surveys, our ability to estimate population characteristics, such as abundance at age, is affected by multiple levels of sampling (i.e. the number of sets, lengths and ages sampled in a survey). We therefore need to assess the impact of haul design and length and age sampling on survey accuracy to determine optimal sampling effort. In this study we simulated repeated stratified-random samples from a spatially correlated field of simulated fish. These samples were then analyzed and estimates of abundance at age were compared against a known truth. By varying the sampling protocol, we demonstrate that increasing the number of sets conducted per stratum provides the greatest gains in precision when sampling a clustered population. Increasing length and age sampling efforts also improved abundance estimates, but to a lesser extent. These results indicate that length and age sampling efforts for some species(e.g. cod *Gadus morhua*) in the trawl survey conducted by regional fisheries management organizations can be scaled back without significant losses to precision. Time saved by reducing said sampling may afford more time to conduct additional sets and/or increase sampling efforts of other species. While this simulation is tailored to a specific case, the method may be adapted to different systems and survey procedures.

**Keywords** - length and age distribution; simulation; spatial correlation; stratified analysis; statistical assessment models; survey design

# Introduction

Fisheries-independent trawl surveys have become an increasingly important research tool for the management of dynamic fish stocks. These surveys provide reliable indices of population abundance as well as estimates of various population characteristics such as length and age frequencies [@Pennington1998]. While costly to obtain, this information forms the basis of of many stock assessments models used throughout the world. Effective and informed management decisions therefore require surveys that maximize information while minimizing the expense of data collection. Determining the number of samples required to adequately characterize a fish population is particularly challenging since data tend to be collected across one or more stages [@Aanes2015]. Optimal survey design is further complicated by the fact that trawls sample clusters of fish that tend to have similar characteristics, such as length, age and stomach contents. This phenomenon results in samples with positive intra-haul correlation, which can markedly reduce the effective sample size for estimating length and age frequencies of the target population [@Pennington1994; @Pennington2002; @Stewart2014]. The complexities of multi-stage sampling and intra-haul correlation make it difficult to answer the question *"how much sampling is enough?"*  

Two main approaches have been applied to try and answer this question: one involves statistical estimators of effective sample size [@Pennington2002; @Stewart2014], and the other employs resampling methods to test alternate sampling protocol [@Cervino2006; @Zhang2013]. Both approaches have shown that lengths are usually oversampled and a reduction in said sampling can often be done without significant loss of accuracy [@Pennington2002]. The same result holds for other positively correlated characteristics, such as age [@Coggins2013] and stomach contents [@Bogstad1995]. Pennington and Vølstad [-@Pennington1994] concluded that the best way to improve the accuracy of surveys with strong intra-haul correlation is to take fewer samples per sampling unit and increase the total number of sampling locations. Few studies, however, have tested these conclusions using simulations. A key advantage of a pure simulation approach is that "true" population size and all stages of sampling can be controlled (set, length and age sampling protocol). The relative effects of each stage of sampling on our perception of the "truth" can then be tested. This level of testing is of particular importance for age composition estimates, and the contemporary age-based assessment models that rely on these estimates, as they are affected by all stages of sampling. A key challenge, of course, is building a simulation that emulates reality.  

The objective of this paper is to use a realistic simulation to evaluate the efficacy of various sampling protocol. First we simulated a spatially autocorrelated target population, and then we simulated surveys over this field. Set density was varied across surveys, as was length and age sampling efforts. Estimates of abundance at age were then obtained using a standard stratified approach [@Smith1981] and deviation from the truth was assessed. Given previous findings, we predict that the greatest gains in precision will come from increasing the number of hauls; increased sampling of correlated variables (length and age) on a set by set basis will be relatively ineffective. The bottom trawl survey of cod (*Gadus morhua*) in NAFO division 3Ps, Newfoundland, was used as a case study for this analysis. While our case study is specific, we also hope that the approach presented here will provide a framework for optimizing sampling protocol for an array of species with different life-histories and distributions. To facilitate future work and collaborations, we have developed an R package for conducting the tests presented in this paper (https://github.com/PaulRegular/SimSurvey).

# Methods

## Simulate abundance

The simulation presented here starts with a common cohort model where the abundance at age $a$ in year $y$ ($N_{a,y}$) equals the abundance of that cohort in the previous year multiplied by the survival rate, which is expressed in terms of total mortality ($Z_{a,y}$):

$$N_{a,y} = N_{a-1,y-1} e^{-Z_{a-1,y-1}}$$
Here, numbers-at-age in the first year are filled via exponential decay, $N_{a,1} = N_{a-1,1} e^{-Z_{a-1,1}}$, numbers at age 1 (i.e. recruits) vary around a baseline value, $log(N_{1,y}) = log(\mu_r) + \epsilon_{y}$, and total mortality is set to a baseline level plus process error, $log(Z_{a,y}) = log(\mu_Z) + \delta_{a,y}$. The error around the recruitment process was set to follow a random walk, $\epsilon_{y} \sim N(\epsilon_{y - 1}, \sigma_{r}^{2})$, and the process error was simulated using the covariance structure described in Cadigan [-@Cadigan2016], $\delta_{a,y} \sim N(0, \Sigma_{a,y})$. The covariance across ages and years is controlled by a process error variance parameter ($\sigma_{\delta}^2$) along with age and year correlation parameters ($\varphi_{\delta, age}$ and $\varphi_{\delta, year}$, respectively). This structure allows for autocorrelation in process errors across ages and years (i.e. total mortality can be made to be more similar for fish that are closer together in age and time). Overall, this  formulation allows for the simulation of an array of population dynamics that one might expect to observe.

## Simulate spatial distribution

The next step in the simulation is to distribute the abundance-at-age matrix simulated using the cohort model throughout a spatial field. Here, a grid of $s$ locations was generated with a resolution of $r$ and a depth gradient. The depth gradient was set-up to have a sigmoid shape with a depth range of $[d_{min}, d_{max}]$, shelf depth of $d_{shelf}$ and a shelf width of $w_{shelf}$. The simulated population is distributed through the grid by simulating spatial-temporal noise controlled by a parabolic relationship with depth and covariance between ages, years and space

$$\begin{aligned}log(N_{a,y,s}) &= log(N_{a,y}) + \eta_{a,y,s} \\ \eta_{a,y,s} &= \frac{(d_s - \mu_{d}) ^ 2}{2 \sigma_d^2} + \xi_{a,y,s} \end{aligned}$$

Where $d_s$ is the depth in a specific cell of the grid, $\mu_d$ is the mean depth where abundance is typically highest and $\sigma_d$ controls the width or dispersion of abundance around the mean. This helps simulate depth preferences of particular fish. Residual noise $\xi_{a,y,s}$ is added to this depth relationship using a combination of Matérn covariance, to control the level of spatial aggregation, and the age-year covariance described in Cadigan [-@Cadigan2016], to control the level of similarity in distributions across ages and years. Spatial correlations was controlled by a smoothing ($\lambda$) and scaling parameter ($\kappa$) [@Blangiardo2015] and correlation across ages and years was controlled by $\varphi_{\xi, age}$ and $\varphi_{\xi, year}$, respectively. The overall variance of the process was controlled by $\sigma_{\xi}^2$. In short, this formulation allows control of depth preferences, the level of spatial aggregation and the amount of age and year specific clustering. Note that $\eta_{a,y,s}$ is forced to sum to one in each year to ensure that the total population of each age for each year through the grid equals the number simulated by the cohort model. Also note that numbers were rounded such that a discrete number of fish are in each cell of the grid. A more detailed description of the space-age-year covariance is included in Appendix 1.

## Simulate survey

The final step in the simulation is to conduct a stratified random survey over the age-year-space array generated using formula described above. First, the grid is divided into $N_{div}$ divisions and $N_{strat}$ depth-based strata. The area of each strata is calculated and this is used to define the sets to allocate to each strata under a particular set density, $D_{sets}$. The allocated number of cells are randomly selected in each strata and the number of fish caught in each set is calculated by applying binomial sampling of the fish in each sampled cell by the proportion of the area covered by the trawl and the catchability of each age:

$$n_{a,y,s} \sim Bin(N_{a,y,s}, \frac{A}{r^2} q_a )$$
Where $n_{a,y,s}$ is the number of fish sampled by a set, $A$ indicates the area covered by the trawl, $r$ is the resolution of the grid cells, and $q_a$ is the catchability coefficient of each age. Here, catchabilities were defined using a logistic curve controlled by a steepness, $k$, and midpoint parameter, $x_0$. The lengths of the fish sampled by the set are then simulated using the original von Bertalanffy growth curve [@Cailliet2006]:

$$log(l) = log(l_{\infty} - (l_{\infty} - l_0) e^{-Ka}) + \varepsilon$$
Where $l_{\infty}$ is the mean asymptotic lengths, $l_0$ is length at birth, $K$ is the growth rate parameter and the error is assumed to follow the normal distribution, $\varepsilon \sim N(0, \sigma_{l}^2)$. Depending on the number of fish caught, sub-sampling is then conducted. Specifically, a maximum number of lengths are measured per set, $M_{lengths}$, and a maximum number of ages, $M_{ages}$, are sampled per length group, $l_{group}$, per division.

## Simulation settings

Ideally the parameter settings used here would be based on model fits to real data, however, conditioning the operating model described above was outside the scope of this project. Moreover, many of the parameters described above may not be identifiable or it may be difficult to obtain un-biased estimates [e.g. bias introduced by length-stratified sampling complicate the fitting of growth models; @Morgan1997]. As such, parameters were informally selected to roughly correspond to observations typically obtained by the Fisheries and Oceans Canada survey of cod in NAFO division 3Ps, Newfoundland. Though this approach is far from exact, the goal was to approximate the life-history and distribution of an actual population to simulate an arena for testing the consequences of surveys with different sampling protocol. Parameter settings and descriptions used in this case study are presented in Table \@ref(tab:test). 


# Tables

Table: (\#tab:test) Parameter descriptions, symbols and settings used in the cod case study.

**Parameter name**   **Symbol**   **Setting**
------------------   ----------   -----------
              Ages          $a$          1:20
             Years          $y$          1:20
  Mean recruitment      $\mu_r$           30M
         

          


# Acknowledgements

- Feedback and advice: Alejandro Buren, Mariano Koen-Alonso, Karen Dwyer, Joanne Morgan, Geoff Evans, Don Power, Brian Healey, Martha Robertson, Danny Ings, Don Stansbury, Mark Simpson, Derek Osborne, Peter Upward, Brad Squires, Dwayne Pittman, Paul Higdon
- Dave Cote for a review of a previous version of this manuscript

# Appendix 1: age-year-space covariance

The simulation applied in this paper was set-up to control covariance across ages, years and space. To do this we used a combination of Matérn covariance, to control the level of spatial aggregation, and the age-year covariance described in Cadigan [-@Cadigan2016], to control the level of similarity in distributions across ages and years. As described in Appendix A in Cadigan [-@Cadigan2016], the age-year covariance can be broken down into a series of AR(1) processes. We integrate Matérn covariance into this series of equations:

$$\xi_{a,y,s} \sim \left\{\begin{matrix} MVN\left (0, \frac{\sigma_\xi^2}{(1 - \varphi_{age}^2)(1 - \varphi_{year}^2)} \boldsymbol{R}_s \right ) & a = 1, y = 1 & \\  MVN\left (\varphi_{year} \xi_{1, y - 1, s}, \frac{\sigma_\xi^2}{(1 - \varphi_{age}^2)} \boldsymbol{R}_s \right ) & a = 1, y > 1 & \\ MVN\left (\varphi_{age} \xi_{a - 1, 1, s}, \frac{\sigma_\xi^2}{(1 - \varphi_{year}^2)} \boldsymbol{R}_s \right ) & a > 1, y = 1 & \\ MVN\left (\varphi_{year} \xi_{a, y - 1, s} + \varphi_{age} (\xi_{a - 1, y, s} - \varphi_{year} \xi_{a - 1, y - 1, s}), \sigma_\xi^2 \boldsymbol{R}_s \right ) & a > 1, y > 1 & \end{matrix}\right.$$

Where $MVN$ indicates the multivariate normal distribution, $\sigma_\xi^2$ controls the variance of the process, $\varphi_{\xi, age}$ and $\varphi_{\xi, year}$ control correlation in the age and year dimension and $\boldsymbol{R}_s$ is defined by Matérn correlation:

$$\boldsymbol{R}_s = \frac{2^{1-\lambda}}{\Gamma(\lambda)} (\kappa \left |s_i - s_j \right|) K_{\lambda}(\kappa \left |s_i - s_j \right|)$$
where $\left |s_i - s_j \right|$ is the Euclidean distance between two locations, $\Gamma$ is the gamma function, $K_{\lambda}$ denotes the modified Bessel function of the second kind, and $\lambda$ and $\kappa$ control the smoothness and scale of the spatial process [@Blangiardo2015]. With this structure, simulated error is correlated across ages, years and space.


# References




































